# for manual http tests
# VS code REST Client is required

GET http://localhost:3000/api/secret/VWMwd2dwOWIwRDFiUDdQNGY3YUZQQTNvZTdIRXA3cGlndmUzeVhwd1p6Tk9vT3dzSXBPdk03S2N3SXFHbjIvVnBHdFE
###

POST http://localhost:3000/api/secret
content-type: application/json

{
    "secret": "Ferenc for full stack developer! :)",
    "expireAfterViews": 1,
    "expireAfter": 1
}