# for manual http tests
# VS code REST Client is required

GET http://localhost:3000/api/secret/SFhMNFpIZzZxMC9vS0NUbjgzMndaUHIrQytLS3JmV1R0T0JrcU44TA
###

POST http://localhost:3000/api/secret
content-type: application/json

{
    "secret": "Secret message",
    "expireAfterViews": 0,
    "expireAfter": 0
}