GET http://localhost:3000/api/secret/hassssh

###

POST http://localhost:3000/api/secret
content-type: application/json

{
    "hash": "hassssh",
    "expireAfterViews": 2,
    "expiresAt": "2021-07-24T16:38:58.430Z"
}