GET http://localhost:3000/api/secret/1
###

POST http://localhost:3000/api/secret
content-type: application/json

{
    "secret": "nemtommicsoda de az már tuti valami hejjhejjhejj",
    "expireAfterViews": 1,
    "expireAfter": 0
}